spring:
  application:
    name: spring-cloud-eureka-second-client
server:
  port: 44040
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
