spring:
  application:
    name: spring-cloud-eureka-second-client
server:
  port: 44040
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#    status-page-url-path: /info
#    health-check-url-path: /health
